### ISSUE TITLE
Cannot change file names

### ISSUE THREAD

**Issue by foxsam21** [cdr/code-server#1059]
- `code-server` version: 
```
~ $ ./code-server -v
info  2.1523-vsc1.38.1
info  22058c5f861d6f39bc42a768d5cb65ffdf696ed1
info  x64
```
see included images for more.

- OS Version: 
`Linux Mint 18 Sarah` on the server side.
## Description
When I connect remotely to code-server host and right click to create a new file __*or*__ rename the filename becomes editable for a second and then the entire explorer panel greys out and stays that way.
## Steps to Reproduce

1. open browser to http://<my_hostip>:<my_port>
2. right click on folder to create new file

PS there also seems to be a confusion as to what version I have. And code-server is trying to update but I have the latest version.
This is from clicking `help|about`.
![about](https://user-images.githubusercontent.com/11862524/66284154-8ffc6f00-e894-11e9-879c-de368899e616.png)
this is output in bash of `./code-server -v` as posted above.
![bash](https://user-images.githubusercontent.com/11862524/66284155-8ffc6f00-e894-11e9-94a2-f95fd5e90650.png)
this is the notification that it is upgrading and an accompanying error to that upgrade.
![error](https://user-images.githubusercontent.com/11862524/66284157-90950580-e894-11e9-9549-ab2d3f8d6a13.png)

EDIT:
I tried docker (have to add `--net=host` to access from remote client) and it works as expected without the problem of editing filenames. (the confused version is still there)

**Comment by Merith-TK** [comment]
The update error appears to be a small bug, trying to get the latest STABLE release, which is still v1.

Screenshots of what you mean by "greyed out" would be nice

**Comment by foxsam21** [comment]
I didnt want to screenshot the directory I was having trouble with. So I switched to a generic directory (/tmp, after that I tried /home/<my_user>) and I found out it only happens in that specific directory. I don't know what to look for in that specific folder...

To describe the "greyed out" a little better. When you originally click on a file to rename it a text box appears where the filename was and all the other files get sort of grey. They are still enabled and work. So here the same thing happens and then the text box disapears. The filenames are grey but they still work. I can even click rename again and it will happen again that the text box dissapears (they are already grey so that doesn't change the second time around).

**Comment by foxsam21** [comment]
OK. I tested a little more and looked at the logs, I checked the logs earlier but didn't know what I was looking for, I was able to stop this from happening. I think it's still a bug. There were some files that were being updated outside of code-server and when the file got refreshed is when I had the problem. I temporarily disabled the service that was writing to the file and it worked fine.

**Comment by sr229** [comment]
Triaged. Can confirm this exist on v2 preview builds.

**Comment by foxsam21** [comment]
is there a way to tell code-server to ignore a certain file?

**Comment by Merith-TK** [comment]
normal vscode settings should do,

—Merith

**Comment by foxsam21** [comment]
OK. that worked. It's a workaround but for me it works now having those files ignored.

**Comment by antofthy** [comment]
So this happens when files get updated outside code-server?
This could be important to me as my users can sftp to upload/download files they may be using.

**Comment by foxsam21** [comment]
That's my experience. But I don't know if it has to do with how the file changed or something else specific to this circumstance. I was using code-server in my homeassistant directory and it has something to do with the database file. I just tried a script that `echo`s to a file every 2 sec. and even with that file open and seeing the lines get added I was not able to reproduce the problem.

However I tried with a script that `touch`ed a new file every 2 seconds and I was able to reproduce the problem. So it seems like a problem of new files being added. I didn't realise that when I ignored the file I ignore `<file_name>.*` so it also ignored similar named  files that were getting added which was the real problem

**Comment by sr229** [comment]
I think this is something to deal with how VSCode Remote handles filesystem changes. Might need more investigation though.

Escalating to high priority as showbreaking bug.

**Comment by code-asher** [comment]
Looks like this was fixed in 1.39.1 so we should update ASAP.

**Comment by foxsam21** [comment]
I am using local copy version:
```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
```
with remote-development plugin and I still have the problem.

**Comment by sr229** [comment]
@foxsam21 we don't use vscode-remote source so their bug does not apply to us.

**Comment by foxsam21** [comment]
ok. That's great. looking forward.

**Comment by code-asher** [comment]
Well actually I could be wrong about it being fixed in 1.39.1. It might only be fixed in the latest insiders.

**Comment by code-asher** [comment]
I tried 1.39.1 and insiders and they both have the same fix. For clarity, the issues is a VS Code bug where the rename overlay gets stuck when the file tree receives an update (like a new file). In the latest version the overlay gets removed when the tree updates. It's a bit unfortunate because it means a rename is completely cancelled when the tree updates but at least it doesn't get stuck.

**Comment by code-asher** [comment]
Fixed in latest master. The update error is also fixed in latest master. Should have a new pre-release out soon.
