### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by jitheshkt** [cdr/code-server#1223]
- `code-server` version: code-server2.1692-vsc1.39.2-linux-x86_64.tar.gz
- OS Version: Ubuntu 18.04.3 LTS / Azure

## Description

First of all, I can see that this issue is being already reported a few months back and it is solved as per my findings. However, I still have it. I am just starting code-server on the `8443` port on my vps. Release file I am using is `code-server2.1692-vsc1.39.2-linux-x86_64.tar.gz`

Starting on http and I am getting the login page but once I enter the password and go further I will get an indefinite loading screen. I have the following error always on the console:

`Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' blob:".`

**Comment by unfor19** [comment]
Same here, the browser loads code-server but getting 300-400 errors of CSP as mentioned above

**Comment by sr229** [comment]
Can't really replicate this, even running it in remote does not yield the expected results. Seems a really weird edge case.

**Comment by unfor19** [comment]
Here's how it looks like.
The weird thing in my case, it loads some of the fonts, but not all of them

![code-server-errors](https://user-images.githubusercontent.com/15122452/72931716-0f8c4c00-3d67-11ea-8130-992a26254948.png)

**Comment by sr229** [comment]
@code-asher can you investigate for a bit? I don't think I can replicate it in my end.

**Comment by code-asher** [comment]
I'm not currently able to replicate but I've seen this happen before
when code-server fails to start VS Code. Could someone with the issue
check code-server's stdout and see if it says anything?

**Comment by nhooyr** [comment]
Please feel free to reopen if this is still an issue. If it is, make sure to check code-server's output as @code-asher mentioned.

**Comment by EnKrypt** [comment]
This started happening to me out of the blue.

No output from code-server.

The strange bit is that it works fine if I open a Private (incognito) window on Firefox, but if I open a regular window, it doesn't work and shows me a white screen. Even when I clear all site data, cookies, cache etc, the result is the same, which is VERY weird.

What variables remain even after all site data is cleared that would give a different outcome in a normal window and a private window?

Here's what shows up on the browser console when this happens.

![cdr](https://user-images.githubusercontent.com/1106939/75622022-c0390700-5bc1-11ea-9d46-2bf7280616f8.png)

code-server seems to be cursed when used with Firefox.

**Comment by kylecarbs** [comment]
Seems like a CSP problem. Any ideas @code-asher ?

**Comment by nhooyr** [comment]
Believe we've fixed this in the restructure branch which should be merged soon but please double check @code-asher

**Comment by code-asher** [comment]
I've been able to unreliably reproduce this in both v2 and v3 (seems
highly timing dependent), but in my testing v2 crashes and v3 recovers
after a refresh so it seems partially solved.

**Comment by mikelxc** [comment]
`proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;`
Adding these to my Nginx config solves my problem

**Comment by alexandrebuisson** [comment]
@mikelxc thx !
