### ISSUE TITLE
Keyboard not being shown automatically on iOS

### ISSUE THREAD

**Issue by DeaDCaTsSociety** [cdr/code-server#1277]
- `code-server` version: 1.39.2
- OS Version: iOS 13

## Description
The browser doesn't matter, I confirm Safari/Firefox/Chrome.
[Recorded Video](https://www.youtube.com/watch?v=hFZc3cRwTo0)

### Korean input bug
Korean is a combination letter. (ㄱ + ㅏ -> 가, ㄴ + ㅏ -> 나)
When entering Korean in the code-server, all the processing of combinations will be input.
It means, When I input 가나, It will be input like this: ㄱ가간나

### Keyboard not shown bug
When I dismiss the keyboard in the edit window, the keyboard does not appear when you press other letters in the edit window.
The keyboard comes up again when I change the scope by pressing a different menu or window.

### Menu button bug
This bug not only iOS but also Mac safari.
Each time I press the top left menu button, the menu button moves up and never return.

![Screen Shot 2020-01-15 at 2 20 57 AM](https://user-images.githubusercontent.com/1787490/72366564-d720b880-373d-11ea-96d2-3a069c2c5745.png)
![Screen Shot 2020-01-15 at 2 21 03 AM](https://user-images.githubusercontent.com/1787490/72366578-e142b700-373d-11ea-80de-28c7117a312d.png)
![Screen Shot 2020-01-15 at 2 21 12 AM](https://user-images.githubusercontent.com/1787490/72366584-e43da780-373d-11ea-9d74-b88315a96921.png)

### Korean input bug
1. Open code-server page from iOS
2. type korean

### Keyboard show bug
1. Open code-server page from iOS
2. Press editor (It will be keyboard shown)
3. Dismiss Keyboard
4. Press editor (It will not be keyboard shown)

### Menu button bug
1. Open code-server page from iOS/Mac Safari
2. Press left top menu.

**Comment by sr229** [comment]
Might be a issue with upstream as well.

**Comment by nhooyr** [comment]
> Korean input bug

That should be fixed, it was an issue with upstream, please try the latest version.

> Keyboard not shown bug

Will test this soon.

> Menu button bug

Fixed in latest.

**Comment by DeaDCaTsSociety** [comment]
Korean input bug still alive in docker tag 2.1698
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1787490/73267358-3d1c3e00-421c-11ea-9e94-808235046d75.png">

**Comment by nhooyr** [comment]
@code-asher

**Comment by nhooyr** [comment]
Confirmed the keyboard showing up working in English. Just not after you hold something down.

Will test Korean soon.

**Comment by nhooyr** [comment]
So confirmed this is an upstream issue with vscode-web

**Comment by DeaDCaTsSociety** [comment]
Sorry guys I combine 3 issue to one

**Comment by nhooyr** [comment]
No worries I separated it out into different issues for you.

**Comment by maekporydzaj** [comment]
Is this issue resolved? I’m facing same problem.

**Comment by code-asher** [comment]
There still seem to be keyboard issues in iOS (https://github.com/search?q=repo%3Amicrosoft%2Fvscode+keyboard+ios&type=issues) but I am not sure if this specifically is still one of them.  If you do not find this specific issue and are able to reproduce on Codespaces or vscode.dev then it would make sense to open a new issue upstream!
