### ISSUE TITLE
SFTP updated version request as the current one seems broken, link below 

### ISSUE THREAD

**Issue by Rathna-K** [cdr/code-server#1716]
I saw a closed issue and I am able to install the extension but it is not working and there is an updated version. Currently the extension shows V1 but there is a 1.12.9 now. Can this be updated? 
Links to extension: 
```
https://marketplace.visualstudio.com/items?itemName=liximomo.sftp
```

**Comment by cmoog** [comment]
Thank you for your request. It looks like the extension repository stopped tagging releases after 1.0.0. Nevertheless, I've pushed version 1.12.9 to the `code-server` extension marketplace.

**Comment by Rathna-K** [comment]
It’s still not pulling the latest and only shows 1.0.0. Any idea why?

**Comment by Rathna-K** [comment]
I think it installed 1.0.0 by default. Looks like I can select install different version. But I think it should pull the latest by default.

**Comment by Rathna-K** [comment]
Hello again! The current lilmoxo sftp is broken and this is a forked version of the same. Can we please make this available? Currently doesn’t show up in the search. https://github.com/Natizyskunk/vscode-sftp/releases/

**Comment by jsjoeio** [comment]
@Rathna-K we are not updating extension in our custom marketplace because we're hoping to move to Open VSX. 

Please install this via the `.vsix` manually. Thanks!
