### ISSUE TITLE
404 when code-server is downloading a newer release

### ISSUE THREAD

**Issue by keiththomps** [cdr/code-server#1746]
When prompted to install a new version through the UI I'm receiving a 404 error downloading the newest release. It appears to be caused by the versions 3.30 and later being tagged with a `v3.3.0` but the associated release file name doesn't include the `v`.

Here's the URL being used to download the newest release vs the newest release's actual URL:

Attempted (404 error): https://github.com/cdr/code-server/releases/download/v3.4.0/code-server-v3.4.0-linux-x86_64.tar.gz
Actual: https://github.com/cdr/code-server/releases/download/v3.4.0/code-server-3.4.0-linux-x86_64.tar.gz

This could be "fixed" in the code [here](https://github.com/cdr/code-server/blob/master/src/node/app/update.ts#L332), but it might just be a consistency issue that can be addressed moving forward by adjusting the tag names and files to match.

- Web Browser: Chrome
- Local OS: macOS 10.15.4
- Remote OS: CentOS 7.8.2003
- Remote Architecture: x86_64
- `code-server --version`: 3.2.0

**Comment by hasip-timurtas** [comment]
The same for me

**Comment by liaocyintl** [comment]
The same for me from +1

**Comment by nhooyr** [comment]
Should just work now!

**Comment by nhooyr** [comment]
Published https://github.com/cdr/code-server/releases/tag/3.4.0

Sorry about this!

**Comment by KolyaKorruptis** [comment]
I think this is a misunderstanding. The URL requested by code-server has a "v" before the version number, inside the file name. And that's what we need to update. A filename with "v3..4.0" in it.  
Removing the "v" from the tag won't help unfortunately.

When this is fixed, these URLs should work: 
https://github.com/cdr/code-server/releases/download/v3.4.0/code-server-v3.4.0-linux-x86_64.tar.gz
https://github.com/cdr/code-server/releases/download/v3.4.0/code-server-v3.4.0-linux-arm64.tar.gz

**Comment by nhooyr** [comment]
It has a v because it’s filling the latest release tag into the template. With the v removed it should just work.

**Comment by nhooyr** [comment]
Argh this is going to break the install script though. 🤦🏻‍♂️

**Comment by nhooyr** [comment]
Fixing.

**Comment by KolyaKorruptis** [comment]
In any case, it didn't find an arm64 release.
![20200602_232548](https://user-images.githubusercontent.com/4076947/83571732-95e04800-a528-11ea-8ef0-910c8d6b53f2.jpg)
![20200602_232618](https://user-images.githubusercontent.com/4076947/83571727-94af1b00-a528-11ea-8fef-b599d32fdd3c.jpg)

**Comment by nhooyr** [comment]
Should be fixed as part of the install script fixes.

**Comment by nhooyr** [comment]
i.e literally just fixed a few seconds ago

**Comment by KolyaKorruptis** [comment]
It's still failing here. 
Requested URL: https://github.com/cdr/code-server/releases/download/3.4.0/code-server-3.4.0-linux-arm64.tar.gz
Actual URL: https://github.com/cdr/code-server/releases/download/3.4.0/code-server-3.4.0-linux-arm64.tar

So close!

**Comment by nhooyr** [comment]
****

macOS ungzipped it automatically. 🤦

**Comment by KolyaKorruptis** [comment]
Hehe. Thank you for your patience.

**Comment by nhooyr** [comment]
@KolyaKorruptis No thank you!

Please give it a shot now!

**Comment by KolyaKorruptis** [comment]
I'm on it. It prompted for the update, I accepted and waited a while, then got a message "Failed to fetch". Same on the second try.

Then VSCode said it lost the connection. When I closed it and tried to run it again, it wouldn't start anymore. `/bin/code-server: 25: exec: /usr/lib/code-server/../lib/node: not found`
![Screenshot_20200603-000023_Termux](https://user-images.githubusercontent.com/4076947/83574309-831c4200-a52d-11ea-88f3-93aaa68e052b.jpg)


Maybe it's my weird setup. I'm on Ubuntu which runs inside Termux [Proot](https://wiki.termux.com/wiki/PRoot) on a Smartphone. 
At the end of the screenshot you can see the files in the code-server dir.

**Comment by KolyaKorruptis** [comment]
It seems to have gotten the download anyway. But the installation went sideways somehow.

**Comment by KolyaKorruptis** [comment]
I installed 3.4.0 manually and got the same error. 
Then I manually installed 3.3.1 and got the same error.
Then I reverted to 3.2.0 which worked. I guess this is one of the breaking changes in v3.3.0 that I'm running into.

**Comment by nhooyr** [comment]
Ahh I see. The problem is you're symlinking to the symlink.
If you change your symlink in `/bin/code-server` to point to `/usr/lib/code-server/bin/code-server` it'll work.

**Comment by nhooyr** [comment]
I'll be sure to fix this in the next release.

**Comment by KolyaKorruptis** [comment]
I updated again from 3.2.0 and everything just worked flawlessly, presumably due to your fix for recursive symlinking. Thank you!

**Comment by nhooyr** [comment]
Glad its working for you!

Oddly enough though I haven't merged my change in and replaced the releases so I'm not sure why it started working for you.

**Comment by KolyaKorruptis** [comment]
Not sure then. I just replaced the symlink, as you suggested, but only after a successful update.

**Comment by nhooyr** [comment]
New release is out!

**Comment by HuJK** [comment]
It told me Do not use, scroll down to v3.4.1, what happen If I use it? Because I use a script to auto update code-server
```
curl -s https://api.github.com/repos/cdr/code-server/releases/latest \
| grep "browser_download_url.*linux-x86_64.tar.gz" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i - -O code-server.tar.gz
```
and it seems work fine. Just curious will it cause any problem that idk if I use 3.4.1 instead of v3.4.1?

**Comment by nhooyr** [comment]
@HuJK Only the tags with `v` prefixed will be kept in future versions. There isn't anything that'll go wrong now but please don't rely on them to avoid breakage.
