### ISSUE TITLE
Java Extension Pack Installation Failure

### ISSUE THREAD

**Issue by mesutcelik** [cdr/code-server#189]
- `code-server` version: 
latest docker image
https://hub.docker.com/r/codercom/code-server/tags

- OS Version: 
Official Docker Image
https://hub.docker.com/r/codercom/code-server/tags
- Extension: 
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

## Description
Java Extention pack can not be installed into locally launched docker container

## Steps to Reproduce
1. docker run -t -p 127.0.0.1:8443:8443 -v "LOCAL_PATH:/root/project" codercom/code-server
2. login code-server
3. search `Java Extention pack` and click install.
4. see the error message on the bottom right. `Failed to install 'vscjava.vscode-java-pack'.
5. The same extension can be installed without an issue with MacOS version of VSCode

**Comment by sr229** [comment]
@mesutcelik does this also happen in a local install? (You can try this via a VM).

**Comment by yasinuslu** [comment]
@sr229 I can confirm that it also happens with the binaries downloaded from https://github.com/codercom/code-server/releases

**Comment by andymaier** [comment]
In my case I get this message:

`Unable to install because, the extension 'redhat.java' compatible with current version '1.33.1' of VS Code is not found.`

Anybody now a workaround?

**Comment by deansheather** [comment]
This will hopefully be fixed in the next version of code-server.

**Comment by code-asher** [comment]
I've been testing out the Java Extension Pack recently on v2 and it appears to be working. It still won't work on v1 though.
