### ISSUE TITLE
Python extension is broken

### ISSUE THREAD

**Issue by abhishekkrthakur** [cdr/code-server#2341]
It seems like the python interpreter cannot be selected in 3.7.1

Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)

**Comment by vnijs** [comment]
Things were working nicely in 3.6.2 but not in 3.7.1 or 3.7.2. With the latest version of the python extension it is trying to also load a jupyter extension and dying there.

![image](https://user-images.githubusercontent.com/2998956/99747942-5a164c00-2a90-11eb-81df-fb1c62c986eb.png)

**Comment by code-asher** [comment]
Looks like we have another broken extension...I wonder why it works in
3.6.2 though. Maybe it's pulling a different version of the Python
extension.

**Comment by zhizheng-1** [comment]
> Looks like we have another broken extension...I wonder why it works in 3.6.2 though. Maybe it's pulling a different version of the Python extension.

I think it started to break with Python 2020.11 where it separated Jupyter into a standalone extension and was dependent on it:
https://github.com/microsoft/vscode-python/releases/tag/2020.11.358366026
"Code for Jupyter Notebooks support has been refactored into the Jupyter extension, which is now a dependency for the Python extension"
The previous python (2020.10) worked for me with code-server 3.7.2.

**Comment by vnijs** [comment]
@zhizheng-1 Thanks! I can confirm that the 2020.10 version (link below) does indeed work with code-server 3.7.2

https://github.com/microsoft/vscode-python/releases/tag/2020.10.332292344

**Comment by bruwozniak** [comment]
The problem I believe is that you are shipping the `2020.12.0-dev` version of the extension in your extension gallery (presumably automatically built from https://github.com/Microsoft/vscode-jupyter), whereas in Microsoft's gallery the versions are different: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter, the latest version is 2020.11.372831992

**Comment by code-asher** [comment]
Ahhhhhh I see. It doesn't look like they use GitHub releases or tags so our builder must just be continually building off master and breaking all the time as a consequence.

**Comment by ttthree** [comment]
Any timeline to get this fixed? :)

**Comment by code-asher** [comment]
No timeline yet; I'm not entirely sure we can do anything differently
from our end other than manually updating the version which won't be
sustainable. Maybe we can get the vscode-jupyter repo to start adding
releases to GitHub, then our marketplace can just pull those in instead
of building itself.

**Comment by vnijs** [comment]
@ttthree I installed the latest extension versions of jupyter and python from marketplace (link below for jupyter) and that seems to work.

https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

**Comment by jhallas** [comment]
I build code-server into a Docker image I use.  I got it working by first installing the python extension (which now automatically installs the 2020.12.0-dev jupyter extension mentioned above from code-server.  I then install the jupyter vsix linked above with --force because it sees it as an older version.  I then add  "extensions.autoUpdate": false to my settings.json file so it doesn't automatically update to the incompatible version upon startup.

**Comment by gogobd** [comment]
@jhallas Could you eventually share the Dockerfile you are using? I've been downgrading to 3.4.1 and for quite a long time now...

**Comment by benz0li** [comment]
@gogobd I'm currently using the following code in a Dockerfile with code-server 3.7.4:

```bash
[...]
&& code-server --install-extension ms-toolsai.jupyter-2020.11.399280825.vsix || true \
&& code-server --install-extension ms-python.python \
[...]
```

See https://github.com/cdr/code-server/issues/2355#issuecomment-737072136 about standard bash ignore error `|| true`.

**Comment by ram-kumar-m** [comment]
> @jhallas Could you eventually share the Dockerfile you are using? I've been downgrading to 3.4.1 and for quite a long time now...

Hmm.. I found 3.5 to work for me!

**Comment by jhallas** [comment]
> @jhallas Could you eventually share the Dockerfile you are using? I've been downgrading to 3.4.1 and for quite a long time now...

Hi, Sorry for the delay.  I can't share the Dockerfile but this is what I do:
1) Install code-server
2) Copy in external vs code extensions
3) code-server --install-extension (python extension)
4) code-server --install-extension (jupyter extension) --force
5) copy custom settings.json to /home/jovyan/.local/share/code-server/User/ with   "extensions.autoUpdate": false line

**Comment by gogobd** [comment]
```
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -fL https://github.com/cdr/code-server/releases/download/v3.7.4/code-server-3.7.4-linux-amd64.tar.gz \
  | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-3.7.4-linux-amd64 ~/.local/lib/code-server-3.7.4
RUN ln -s ~/.local/lib/code-server-3.7.4/bin/code-server ~/.local/bin/code-server
RUN PATH="~/.local/bin:$PATH"

# Fix broken python plugin # https://github.com/cdr/code-server/issues/2341
RUN mkdir -p ~/.local/share/code-server/ && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/settings.json 
RUN wget https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
 && ~/.local/bin/code-server --install-extension ./ms-python-release.vsix || true
```
Thanks to the comments I found here here that made it work for me...

**Comment by gogobd** [comment]
Just realized that settings.json I create doesn't prevent code server from updating to the broken version on startup.

**Comment by pseeth** [comment]
By any chance, is there a timetable for getting the extension working again? I really want to use code-server, but as an ML person trying to use code-server on remote GPUs, the Python extension not working is a showstopper for me. Hoping it gets fixed soon, as I'd love to use this.

**Comment by jhallas** [comment]
@pseeth I think it works even with the most recent version as long as you download the extension vsix for python and jupyter from the vs code website manually install with the considerations I listed.

**Comment by vnijs** [comment]
I can confirm that python + jupyter extension work with code server 3.8.0 if manually downloaded and installed

**Comment by pseeth** [comment]
Hmm, is there documentation somewhere for doing this? I'm not really sure how to apply the fix at all, actually. Regardless, I'd like to migrate more people I work with than just myself to this if possible, so the more automatic the better...

**Comment by peat-psuwit** [comment]
I believe that this is now an extension server's problem. I believe it has to take and build the tagged version, not the moving master. @code-asher, the jupyter extension seems to use [tag/releases](https://github.com/microsoft/vscode-jupyter/releases); it just doesn't release a binary with it. If your system already can build from master, I guess this shouldn't change much. (P.S. is the code-server's marketplace code open-source?)

Note that you should not take the extension from VSCode's official marketplace, as [its ToS](https://aka.ms/vsmarketplace-ToU) potentially prohibits using it for anything other than the official VSCode.

**Comment by J4gQBqqR** [comment]
Hi, I spent my last two days building and reverse proxying a code server container only to find Python debugging is not working in my container. I read that installing vsix is prohibited by TOS. I understand that Jupyter and Pylance extensions are proprietary. 

Could you let us know if the Python extension can be made to work without Jupyter and Pylance? It would be a really useful piece of information to help us choose the route to go in the future. I believe for most Python developers, the unavailability of the Python extension is a dealbreaker.

**Comment by code-asher** [comment]
We haven't done anything for the Python extension in particular but we
are in the process of adding the Open VSX marketplace so code-server
will query it first and then fall back to ours with the goal of
eventually phasing ours out entirely.

@peat-psuwit The marketplace is not currently open source. I believe we
had plans to do so but with the switch to Open VSX I think we might
never get around to it.

For now I think the only workaround is to manually download the vsix to
the machine code-server is running on from the extension's GitHub
repository or find it on Open VSX then use "install from VSIX" from the
UI or `code-server --install-extension path/to/vsix`.

https://open-vsx.org/?search=python&category=&sortBy=relevance&sortOrder=desc

Ideally you'd be able to just set the appropriate environment variables
and use Open VSX now:

```bash
SERVICE_URL="https://open-vsx.org/vscode/gallery" \
  ITEM_URL="https://open-vsx.org/vscode/item" \
  code-server # or something like code-server --install-extension ms-python.python
```

But every time I try that I get an error about a corrupt zip so we'll
have to look into that.

**Comment by peat-psuwit** [comment]
Interestingly, OpenVSX's Python extension is still at version `2020.10` (the last version that works without a separated Jupyter extension), and the Jupyter extension doesn't exist in OpenVSX.

**Comment by TureeZhang** [comment]
> ```
> RUN mkdir -p ~/.local/lib ~/.local/bin
> RUN curl -fL https://github.com/cdr/code-server/releases/download/v3.7.4/code-server-3.7.4-linux-amd64.tar.gz \
>   | tar -C ~/.local/lib -xz
> RUN mv ~/.local/lib/code-server-3.7.4-linux-amd64 ~/.local/lib/code-server-3.7.4
> RUN ln -s ~/.local/lib/code-server-3.7.4/bin/code-server ~/.local/bin/code-server
> RUN PATH="~/.local/bin:$PATH"
> 
> # Fix broken python plugin # https://github.com/cdr/code-server/issues/2341
> RUN mkdir -p ~/.local/share/code-server/ && mkdir -p ~/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/User/settings.json 
> RUN wget https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
>  && ~/.local/bin/code-server --install-extension ./ms-python-release.vsix || true
> ```
> 
> Thanks to the comments I found here here that made it work for me...
> I fixed and edited this comment (settings.json wasn't in the right place)

It works perfect ! Just saved my day , thank you soooo much ! In short, what's the problem python pluign not working as expected is actually because the settings.json file not at the right place before install plugin. 

I used code-server 3.8.0 (actually, what's version you used as docker base image seems doesn't matter as all), and I did the following things solved my problem:

**1. Download** <https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix>, if you are in China, as some reason you know, download from Microsoft maybe more faster → <https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.10.332292344/vspackage> .Two of them is the same file, only name different which doesn't matter.

**2. Create settings.json** beforn install python plugin. Attention, maybe you are not know clearly, "coder" in the path is the username you use in linux. If your user name is "mydev123", "coder" should replace as "mydev123" in the path ,it's depends on your user name.

```shell
# it's a Dockerfile
RUN mkdir -p /home/coder/.local/share/code-server/ && mkdir -p /home/coder/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > /home/coder/.local/share/code-server/User/settings.json
```

**3. Copy and install** step1's file into your Docker image. Attention, 'ms-python.python-2020.10.332292344.vsix' is the filename you may need change, depends on step1 where you download the file.

```shell
#it's a Dockerfile
COPY --chown=coder:coder ms-python.python-2020.10.332292344.vsix /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
RUN code-server --install-extension /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
```

4. After docker build complete, login into code-server, press debug button you will need to select a python interpreter, no more words as you see it ,you know how to.

5. Finnaly, just debug ,it works fine !

![demo](https://user-images.githubusercontent.com/30072809/105379248-9bb9a380-5c47-11eb-98fd-9adcb5fa3f51.png)

**Comment by phisanti** [comment]
Hi @TureeZhang , I am trying to follow you guide but I struggle with where to put the extensions

```
#it's a Dockerfile
COPY --chown=coder:coder ms-python.python-2020.10.332292344.vsix /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
RUN code-server --install-extension /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
```

Here: **whatever-path-you-like**, are we supposed to put a default path for the extensions. If so, how can we figure out where they are before running the container?

**Comment by TureeZhang** [comment]
Hi @phisanti , **whatever-path-you-like** is mean the path inside the container you like. It seems in your error information says ``/var/lib/docker/tmp/docker-builder201615650/ms-python.python-2020.10.332292344.vsix: no such file or directory`` .

I think we should talk about the COPY command in Dockerfile's means first :

```
COPY <filepath-in-your-machine> <filepath-you-want-to-copy-to-inside-docker-container>
```

the first argument are the source, the second are the target inside Docker Image.

So, as your error information says , it seems that under your truly machine directory "/var/lib/docker/tmp/docker-builder201615650", there is actually no any file that named "ms-python.python-2020.10.332292344.vsix" which you should download it from Internet before you execute your docker build progress, you should put "ms-python.python-2020.10.332292344.vsix" that you downloaded under "/var/lib/docker/tmp/docker-builder201615650" directory so when DockerEgine build your Docker , the builder could find it ,then copy it into your Docker Image.

After the extension copied into your Image, ``code-server --install-extension`` will works fine as you expected.

**Comment by phisanti** [comment]
# Issue

I finally was able to install code-server and install the extensions. However, once I am inside of the application, I see that the python/jupyter extensions do not appear as existing, so I have to install them again. Then, when I start a python test.py and run (using ctrl + enter) `import os`, just as a test, I got the following error:
`- command 'python.execSelectionInTerminal' not found`
If I try to manually add the python interpreter (shift + ctrl + p), I got another error:
`- Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)`
If I try to create a new jupyter, then, another error comes:
`- Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)`

So, this gives the impression vscode cannot connect with the extensions. Why?

----------------------------------
# Dockerfile for reproducibility
```dockerfile
FROM codercom/code-server:3.7.4 # I also tried

# Install conda
RUN curl -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b && \
    rm ~/miniconda.sh && \
    /home/coder/miniconda3/bin/conda install conda-build

ENV PATH=$PATH:/home/coder/miniconda3/bin/

# Add extensions
RUN mkdir -p ~/.local/share/code-server/ && mkdir -p ~/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/User/settings.json 
RUN curl -JLO https://github.com/microsoft/vscode-jupyter/archive/2012.11.3.tar.gz  && \
    code-server --install-extension ms-toolsai.jupyter-2020.11.399280825.vsix || true

RUN curl -JLO https://github.com/microsoft/vscode-python/releases/download/2021.1.502429796/ms-python-release.vsix && \
    code-server --install-extension ms-python.python

COPY run.sh /run.sh
EXPOSE 8888
ENTRYPOINT ["/run.sh"]
```

**Comment by sidalla** [comment]
after a struggle, i figured out the version which works

https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806

**Comment by maresb** [comment]
> But every time I try that I get an error about a corrupt zip so we'll have to look into that.

@code-asher could it be that the downloaded archive is in addition .gz-compressed?

I have a Dockerfile where I download various stuff from the marketplace, and for some reason I always have to gunzip it. (See below.)

BTW, people in this thread may find the following excerpt from my Dockerfile to be useful  ;)

```bash
: \
 && PUBLISHER=ms-python \
 && PACKAGE_NAME=python \
 && PACKAGE_VERSION=2020.10.332292344 \
 && FILE_NAME=${PUBLISHER}.${PACKAGE_NAME}-${PACKAGE_VERSION}.vsix \
 && wget -S https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${PUBLISHER}/vsextensions/${PACKAGE_NAME}/${PACKAGE_VERSION}/vspackage --output-document=${FILE_NAME} \
 && mv ${FILE_NAME} ${FILE_NAME}.gz \
 && gunzip ${FILE_NAME}.gz \
 && echo Do something here with the downloaded extension... \
 && rm ${FILE_NAME} \
;
```

**Comment by code-asher** [comment]
Ahhhh interesting. Yeah that could be it!

**Comment by jkquijas** [comment]
Any fix deployed yet?

**Comment by maresb** [comment]
I have success with Python extension 2020.10.332292344 and the latest Jupyter.

**Comment by renardeinside** [comment]
Unfortunately in code-server 3.8.1 Python extension is still broken, so an older version is the only choice. 

Worth mentioning - Python extension with v.2021.X provides support for pylance (which is incredibly great). 
Would be cool if someone takes care of upgrading the underlying version of VS Code and so - the issues with the Python extension will be resolved. 

I've tried to do the upgrade but failed to fix issues raised after making an upgrade. My knowledge of Typescript is too poor to make such a great contribution.

Here is yet another Dockerfile example (both Python and Jupyter are supported):

```
FROM ubuntu:latest

RUN apt update
RUN apt install -y curl wget python3 python3-pip
RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=3.8.1

RUN mkdir -p ~/.local/share/code-server/  \
    && mkdir -p ~/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/User/settings.json 

RUN wget https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
    && code-server --install-extension ./ms-python-release.vsix --force


ENTRYPOINT [ "code-server", "--bind-addr=0.0.0.0:8888"]
```

**Comment by maresb** [comment]
@renardeinside thanks for sharing! I really like that you avoid the Marketplace and download directly from the GitHub release.

As an alternative to PyLance I have installed PyRight, the open-source version. It works quite well under 2020.10.332292344.

To install PyRight, simply run `code-server --install-extension "ms-pyright.pyright"`

It looks to me like we are unfortunately facing the classical [EEE policy](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish), so I fear that these incompatibilities and hybrid licensing terms are only the beginning of our problems. I really want to see the code-server project succeed, so I hope we can fight back and find good workarounds!!!

**Comment by ahmed-abdelazim** [comment]
I installed old version v2020.10.332292344 and worked after reload

**Comment by phisanti** [comment]
I also can confirm that the v2020.10.332292344  version works with code-server v3.8.0. If the version that you download from the marketplace does not run, try using [open vsx](https://open-vsx.org/). If you wanna use conda, go to settings and add the path where conda is located.

However, it really would be a pity to see an EEE policy as @maresb says. I would like to know if there is something we can do about it because setting a workplace with VScode-server is: 1- extremely easy, 2-really good experience.

**Comment by bpmct** [comment]
@jsjoeio With #1473, will this no longer be an issue?

**Comment by jsjoeio** [comment]
I'm not sure, I haven't tested it yet but can take a look once #2659 is merged

**Comment by timluther** [comment]
Hi, I'm having this problem in windows with v2021.2.576481509 of the plugin. I don't know anything about Jupyter, or how to install this via git, so I'm a bit stuck. This is a blocking issue now for a project with a deadline. I'd appreciate any help.

**Comment by gogobd** [comment]
v2020.10.332292344 has been reported to work with 3.8.0, you should be able to install it with code-server --install-extension ...vsix --force somehow in the content of the server

**Comment by timluther** [comment]
> v2020.10.332292344 has been reported to work with 3.8.0, you should be able to install it with code-server --install-extension ...vsix --force somehow in the content of the server

Sorry to be dense but where do I enter that command? It's not something the terminal seems to know about...

**Comment by gogobd** [comment]
> > v2020.10.332292344 has been reported to work with 3.8.0, you should be able to install it with code-server --install-extension ...vsix --force somehow in the content of the server
> 
> Sorry to be dense but where do I enter that command? It's not something the terminal seems to know about...

That’s what I tried to describe with "somehow in the context of the server" i.e. that depends on where the server is running and available as a command. In my own setup that’s inside a Dockerfile but it really depends completely on your environment.

**Comment by timluther** [comment]
> > > v2020.10.332292344 has been reported to work with 3.8.0, you should be able to install it with code-server --install-extension ...vsix --force somehow in the content of the server
> > 
> > 
> > Sorry to be dense but where do I enter that command? It's not something the terminal seems to know about...
> 
> That’s what I tried to describe with "somehow in the context of the server" i.e. that depends on where the server is running and available as a command. In my own setup that’s inside a Dockerfile but it really depends completely on your environment.
I'm not running this in a container or from a dockerfile, it's vanilla windows 10 and I'm not sure about the layout of any client/server relationship between vscode and its plugins, it's not something I've had to look in to. 
Is there anything I can do with this sort of setup, other than wait for an update?

**Comment by zombaratus** [comment]
Hello, @timluther 
It is not vscode. It is code-server. [Here](https://github.com/cdr/code-server/blob/v3.9.0/docs/FAQ.md#differences-compared-to-vs-code) u can get additional info
Probably, you need vanilla visual studio code https://code.visualstudio.com/

**Comment by timluther** [comment]
I'm in the wrong project... doh. Silly me, I googled the error message, it led me here. I apologise for the confusion.

**Comment by RickyWei** [comment]
> > ```
> > RUN mkdir -p ~/.local/lib ~/.local/bin
> > RUN curl -fL https://github.com/cdr/code-server/releases/download/v3.7.4/code-server-3.7.4-linux-amd64.tar.gz \
> >   | tar -C ~/.local/lib -xz
> > RUN mv ~/.local/lib/code-server-3.7.4-linux-amd64 ~/.local/lib/code-server-3.7.4
> > RUN ln -s ~/.local/lib/code-server-3.7.4/bin/code-server ~/.local/bin/code-server
> > RUN PATH="~/.local/bin:$PATH"
> > 
> > # Fix broken python plugin # https://github.com/cdr/code-server/issues/2341
> > RUN mkdir -p ~/.local/share/code-server/ && mkdir -p ~/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/User/settings.json 
> > RUN wget https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
> >  && ~/.local/bin/code-server --install-extension ./ms-python-release.vsix || true
> > ```
> > 
> > 
> > Thanks to the comments I found here here that made it work for me...
> > I fixed and edited this comment (settings.json wasn't in the right place)
> 
> It works perfect ! Just saved my day , thank you soooo much ! In short, what's the problem python pluign not working as expected is actually because the settings.json file not at the right place before install plugin.
> 
> I used code-server 3.8.0 (actually, what's version you used as docker base image seems doesn't matter as all), and I did the following things solved my problem:
> 
> **1. Download** https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix, if you are in China, as some reason you know, download from Microsoft maybe more faster → https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.10.332292344/vspackage .Two of them is the same file, only name different which doesn't matter.
> 
> **2. Create settings.json** beforn install python plugin. Attention, maybe you are not know clearly, "coder" in the path is the username you use in linux. If your user name is "mydev123", "coder" should replace as "mydev123" in the path ,it's depends on your user name.
> 
> ```shell
> # it's a Dockerfile
> RUN mkdir -p /home/coder/.local/share/code-server/ && mkdir -p /home/coder/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > /home/coder/.local/share/code-server/User/settings.json
> ```
> 
> **3. Copy and install** step1's file into your Docker image. Attention, 'ms-python.python-2020.10.332292344.vsix' is the filename you may need change, depends on step1 where you download the file.
> 
> ```shell
> #it's a Dockerfile
> COPY --chown=coder:coder ms-python.python-2020.10.332292344.vsix /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
> RUN code-server --install-extension /whatever-path-you-like/ms-python.python-2020.10.332292344.vsix
> ```
> 
> 1. After docker build complete, login into code-server, press debug button you will need to select a python interpreter, no more words as you see it ,you know how to.
> 2. Finnaly, just debug ,it works fine !
> 
> ![demo](https://user-images.githubusercontent.com/30072809/105379248-9bb9a380-5c47-11eb-98fd-9adcb5fa3f51.png)

It works

**Comment by 7HE-W0R1D** [comment]
Hi @RickyWei glad that you got your problem solved. I ran into the same problem but I'm using a raspberry pi rather than the docker. When you create the settings.json, I saw you just wrote two lines about extension update, I currently have a working setting.json but I still cannot get the extension working. Do we have to put some python related things into the settings file? Are there any other requirements that needs to be fulfilled? (Currently I can run python through code-runner extension and command line, but after I installed the python and jupyter extension, there are no little run button at the corner)
Thanks in advance!

**Comment by wangm23456** [comment]
@RickyWei But I still can't select python interpreter. I use poetry install  virtual environments in projrct dir.

**Comment by goliat43** [comment]
Is there some way to help move this forward or are there some plan for how this could/should work in the future? The workaround of installing a old plugin seems like a poor one in the longer run (even if it works for me right now). Will Python in code-server be a no go? I don't know enough about the ecosystem here to understand what the consequences are but maybe someone that does can give some pointers?

**Comment by jsjoeio** [comment]
Sorry for the issues all. We're trying to switch to OpenVSX but that's proving a larger effort than we anticipated. Unfortunately installing the old plugin is the best workaround we have right now. 

> maybe someone that does can give some pointers

If you want to contribute to this issue and code-server, there are two paths you can go down:
1. You can get code-server running locally and see what issues arise related to the Python extension. Follow the docs [here](https://github.com/cdr/code-server/blob/v3.9.0/docs/CONTRIBUTING.md)
2. If you know Java, you can look at [this issue](https://github.com/eclipse/openvsx/issues/249) we've opened with OpenVSX that we need fixed/implemented before we can switch marketplaces.

**Comment by phisanti** [comment]
Today has been released VS code-server 3.9.1. This new version updates to VS 1.53.2, so going with the recurring question, has anyone tested if it is possible to use python >2020.10.332292344?? Note that I have python working in my divide, I just want to know if it is possible to use the update within this new version.

**Comment by jsjoeio** [comment]
In other news, we're talking to the folks behind Open VSX and they've said they plan to work on adding web extension support this month or next. https://github.com/eclipse/openvsx/issues/249#issuecomment-795411773

**Comment by phisanti** [comment]
Has anyone a trouble making Jupyter work in 3.9.1? 
I installed the 2020.10.33... as:

```docker
RUN wget https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
 && ~/.local/bin/code-server --install-extension ./ms-python-release.vsix || true

```

but when I try to run I cell I get the following error:

```
Failed to connect to Jupyter notebook. http://127.0.0.1:8889/ Error: Kernel Python 3 is not usable. Check the Jupyter output tab for more information.
```

**Comment by maresb** [comment]
@phisanti I am having that problem with code-server 3.9.0 and ms-python v2020.10.332292344. In the Jupyter output, I see several HTTP 403 status codes (forbidden) with the message `'_xsrf' argument missing from POST`. I have not yet looked into it. Did you find an explanation or solution?

**Comment by phisanti** [comment]
@maresb I am still struggling with the issue. I would like to try your solution, but I don't know how did you find the value of your token. If it is the token for the website address, then I tried without success. I really hope that the guys at open-svx release the ms-tools soon!

**Comment by maresb** [comment]
@phisanti since our problem seems to be a distinct issue, I opened #2875. Let's continue discussion there.

**Comment by oxy** [comment]
Hey, I think I managed to get it working - you may need to "reset" your `code-server` instance by removing `~/.local/share/code-server` (warning: this removes any custom configuration, all extensions, and your HTTPS certs if you asked code-server to manage them!), but I just tested this myself and Python *should* work now, fingers crossed.

I did some manual wrangling and downgraded the Jupyter extension and upgraded the Python extension that's being served; it _may_ break every time MS pushes a new update, but I'll force-downgrade it whenever its needed.

Closing for now!

**Comment by Ki6an** [comment]
was facing a similar issue,
by using the older version of python was able to fix the issue :
![image](https://user-images.githubusercontent.com/63173962/111539804-51aaf500-8794-11eb-8293-79bb2d7194a1.png)

next,  select this version `2020.5.86806`.

now I'm able to use `pylint` and `debugging` too

**Comment by maresb** [comment]
@Ki6an it's well known that it works with `2020.10.332292344`, so you shouldn't need to go that far back.

@oxy, could you please provide more details? What are the specific versions of the Jupyter and Python extensions that you're using?

**Comment by phisanti** [comment]
I totally agree with @Ki6an, but the problem is I cannot run ipython widgets in that version. More precisely, I would like to run the [nglview ](https://github.com/nglviewer/nglview) plug-in for my work. Do you know how I could run that widget in the `2020.5.86806 `version? Moreover, what is the difference between the two versions so that the `2020.5.86806 `works but `2020.10.332292344 `doesn't? Is there any "debug" option that we could activate to see how each version runs?

**Comment by oxy** [comment]
Alright, latest versions that work for me are `v2021.2.633441544` and `2021.2.0` - and they should be the latest on our gallery.

**Comment by phisanti** [comment]
I have just tried  `Python v2021.2.633441544 `and `Jupyter 2021.2.0 ` (using `code-server 3.9.1`) as @oxy says and I can confirm that it works. However, I might seem a bit thick but I don't understand why. I thought that code-server depended on open-vsix and they have not released a new version, so why is that suddenly now works?

**Comment by abhishekkrthakur** [comment]
doesnt work for me. im on 3.9.1 and updated python extension to 2021.2.633.....

**Comment by rushtehrani** [comment]
It's also working for me with `code-server 3.9.1` and `ms-python 2021.3.658691958`.

**Comment by oxy** [comment]
> I have just tried `Python v2021.2.633441544 `and `Jupyter 2021.2.0 ` (using `code-server 3.9.1`) as @oxy says and I can confirm that it works. However, I might seem a bit thick but I don't understand why. I thought that code-server depended on open-vsix and they have not released a new version, so why is that suddenly now works?

We were hoping that we could switch from our internal gallery to OpenVSX and then hope upstream/OpenVSX could sort out the versioning issues; but then I decided to just manually override the versions we're serving right now, since we're blocked on web extension support for OpenVSX.

I didn't expect 2021.3 to work as that depends on VSCode 1.54, which we're yet to update to.

**Comment by wzrzt** [comment]
> It's also working for me with `code-server 3.9.1` and `ms-python 2021.3.658691958`.
May I know how to install ms-python 2021.3.658691958 into code-server 3.9.1, please?
I can't see this version on my code-server 3.9.1. And I downloaded it from vscode-extension-market and it can't be installed and told me not compitable with vscode v1.53.2.

**Comment by rushtehrani** [comment]
> May I know how to install ms-python 2021.3.658691958 into code-server 3.9.1, please?
> I can't see this version on my code-server 3.9.1. And I downloaded it from vscode-extension-market and it can't be installed and told me not compitable with vscode v1.53.2.

I went back and checked and it looks like even though I explicitly set the version to `2021.3.658691958`:

```bash
RUN code-server --install-extension ms-python.python@2021.3.658691958
```

In the IDE it's showing that `2021.2.633441544` is installed:

![image](https://user-images.githubusercontent.com/1211823/112022649-bb5a3480-8aef-11eb-8f22-85c78fe815d6.png)

So `--install-extension` probably fell back to the latest supported version.

The good news is `2021.2.633441544` is working.

**Comment by ddurham2** [comment]
@rushtehrani, that's probably due to #2626

**Comment by DavidTWynn** [comment]
After I set an env variable to install python3 I could install 2021.3 of the ms-python extension.

https://github.com/linuxserver/docker-mods/tree/code-server-python3
DOCKER_MODS=linuxserver/mods:code-server-python3

**Comment by gogobd** [comment]
it's weird but all the previous workarounds don't work for me any more... I get ChunkLoadError with 2020.10.332292344/ms-python-release.vsix and everything else I tried didn't work either. Is there a known working solution for docker currently?

**Comment by MarcSkovMadsen** [comment]
I can get `ms-python` v2021.5.842923320 and `ms-toolsai.jupyter` v2021.3.0 working. 

But using the latest version  `ms-toolsai.jupyter` v2021.5.0 does not work.

![image](https://user-images.githubusercontent.com/42288570/120422588-de635900-c368-11eb-85d1-16e2da9ba74f.png)

**Comment by gogobd** [comment]
> I can get `ms-python` v2021.5.842923320 and `ms-toolsai.jupyter` v2021.3.0 working.
> 
> But using the latest version `ms-toolsai.jupyter` v2021.5.0 does not work.
> 
> ![image](https://user-images.githubusercontent.com/42288570/120422588-de635900-c368-11eb-85d1-16e2da9ba74f.png)

Is that with 3.10.x? (I’m asking because I completely downgraded to 3.9.x because Jupyter didn’t work.)

**Comment by MarcSkovMadsen** [comment]
> > I can get `ms-python` v2021.5.842923320 and `ms-toolsai.jupyter` v2021.3.0 working.
> > But using the latest version `ms-toolsai.jupyter` v2021.5.0 does not work.
> > ![image](https://user-images.githubusercontent.com/42288570/120422588-de635900-c368-11eb-85d1-16e2da9ba74f.png)
> 
> Is that with 3.10.x? (I’m asking because I completely downgraded to 3.9.x because Jupyter didn’t work.)

What is 3.10.x referring to?
