### ISSUE TITLE
 I cannot connect to the server.

### ISSUE THREAD

**Issue by dev-gwang** [cdr/code-server#2364]
- Web Browser: Chrome 86.0.4240.198 (64bit)
- Local OS: Windows 10
- Remote OS: Raspbian 10 (Raspberry pi3)
- Remote Architecture: arm
- `code-server --version`:
![image](https://user-images.githubusercontent.com/14958650/100255234-9cef8c80-2f86-11eb-907b-b653c8b8382f.png)

Hello! 😊
When I connect to the server with a web browser, I cannot connect to the server.
![image](https://user-images.githubusercontent.com/14958650/100255395-ca3c3a80-2f86-11eb-8d69-13ffc059a3aa.png)

I could see the error below. (server log)
```
/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:423
l.stderr.setEncoding("utf8").on("data",e=>this.logger.error(e))),l.on("message",e=>{switch(e&&e.type){case"__$console":const t=this.logger[e.severity]||"info";this.logger[t]("console",i.field("arguments",e.arguments));break;case"VSCODE_EXTHOST_DISCONNECTED":this.logger.trace("Going offline"),this.setOffline();break;case"VSCODE_EXTHOST_IPC_READY":this.logger.trace("Got ready message"),this.sendInitMessage(n);break;default:this.logger.error("Unexpected message",i.field("event",e))}}),this.logger.trace("Waiting for handshake..."),l}}})),define(t[178],i([0,1,40,17,66,52,59]),(function(e,t,i,r,n,s,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.Protocol=void 0;class a extends n.PersistentProtocol{constructor(e,t){super(t.skipWebSocketFrames?new s.NodeSocket(e):new s.WebSocketNodeSocket(new s.NodeSocket(e))),this.options=t}getUnderlyingSocket(){const e=this.getSocket();return e instanceof s.NodeSocket?e.socket:e.socket.socket}handshake(){
                                                                                                                                                                             ^

TypeError: this.logger[t] is not a function
    at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:423:174)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2020-11-25T16:24:20.721Z] error VS Code exited unexpectedly with code 1
```

**Comment by code-asher** [comment]
Thank you for reporting, will fix asap.

**Comment by dev-gwang** [comment]
@code-asher 

I want to try it before the next version is released.
How can I do it?

Thank you.

**Comment by nhooyr** [comment]
See the contributing docs linked in the README for the build process @dev-gwang 

Or download the build artifact from @code-asher's PR on github actions.

**Comment by gt2416** [comment]
Same issue for me, glad you guys already reported it.
- System: FreeBSD 12.2

**Comment by code-asher** [comment]
Should be fixed in 3.7.4!

**Comment by nhooyr** [comment]
Turns out this was not fixed, I've been able to reproduce.

I also added a log every time the extension host starts up so that we never miss this in the future.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/commit/d2f3e6cea287e889ca28abfe6e0906450f45e4ef and #2400

**Comment by nhooyr** [comment]
Will be fixed in the next release!
