### ISSUE TITLE
Alpha Program => Error connecting to your code-server instance

### ISSUE THREAD

**Issue by J3n5en** [cdr/code-server#2478]
- Web Browser: chrome 87
- Local OS: macos 10.15.2 
- Remote OS: Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
- Remote Architecture: x86_64
- `code-server --version`: 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

![image](https://user-images.githubusercontent.com/10610925/102464324-2aeefc80-4087-11eb-8356-ec2de2a55189.png)

try to run with `--log debug`. but the  `.local/share/code-server/coder-logs/code-server-stderr.log` is empty.

**Comment by oxy** [comment]
I'm not sure what exactly is happening there - does `code-server` print any logs to the terminal?

**Comment by J3n5en** [comment]
```
# code-server -vvv --link
[2020-12-18T18:18:12.813Z] trace child:6894 got message {"message":{"type":"handshake","args":{"_":[],"bind-addr":"127.0.0.1:8080","auth":"none","password":"xxxxx","config":"/root/.config/code-server/config.yaml","verbose":true,"link":{},"user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","log":"trace","host":"localhost","port":0,"proxy-domain":[],"usingEnvPassword":false}}}
[2020-12-18T18:18:12.816Z] info  code-server 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b
[2020-12-18T18:18:12.817Z] info  Using user-data-dir ~/.local/share/code-server
[2020-12-18T18:18:12.817Z] trace Using extensions-dir ~/.local/share/code-server/extensions
[2020-12-18T18:18:12.832Z] info  Using config file ~/.config/code-server/config.yaml
[2020-12-18T18:18:12.832Z] info  HTTP server listening on http://127.0.0.1:33663 (randomized by --link)
[2020-12-18T18:18:12.833Z] info    - Authentication is disabled (disabled by --link)
[2020-12-18T18:18:12.833Z] info    - Not serving HTTPS
[2020-12-18T18:18:12.833Z] info  Remember --link is a beta feature and requires being accepted for testing
[2020-12-18T18:18:12.833Z] info  See https://github.com/cdr/code-server/discussions/2137
[2020-12-18T18:18:12.833Z] debug running agent with bind,--code-server-addr=127.0.0.1:33663,
[2020-12-18T18:18:13.136Z] info  Proxying code-server to Coder Cloud, you can access your IDE at https://xxxx.cdr.co
```

It seems that there is no useful information😨😨

**Comment by pillows** [comment]
I have the same issue too. I'll post what I can to see if it helps

Web Browser: chrome 87
Local OS: windows 10 20H2
Remote OS: Debian 10
Remote Architecture: x86_64
code-server --version: 3.8.0 c4610f7829701aadb045d450013b84491c30580d

`$ code-server -vvv --link
[2020-12-30T01:39:24.491Z] trace child:4119388 got message {"message":{"type":"handshake","args":{"_":[],"password":"xxx","config":"/home/xxx/.config/code-server/config.yaml","verbose":true,"link":{},"user-data-dir":"/home/pillows/.local/share/code-server","extensions-dir":"/home/xxx/.local/share/code-server/extensions","log":"trace","auth":"none","host":"localhost","port":0,"proxy-domain":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
[2020-12-30T01:39:24.493Z] info  code-server 3.8.0 c4610f7829701aadb045d450013b84491c30580d
[2020-12-30T01:39:24.494Z] info  Using user-data-dir ~/.local/share/code-server
[2020-12-30T01:39:24.494Z] trace Using extensions-dir ~/.local/share/code-server/extensions
[2020-12-30T01:39:24.507Z] info  Using config file ~/.config/code-server/config.yaml
[2020-12-30T01:39:24.507Z] info  HTTP server listening on http://127.0.0.1:4483 (randomized by --link)
[2020-12-30T01:39:24.507Z] info    - Authentication is disabled (disabled by --link)
[2020-12-30T01:39:24.507Z] info    - Not serving HTTPS (disabled by --link)
[2020-12-30T01:39:24.507Z] debug running agent with bind,--code-server-addr=127.0.0.1:4483,
[2020-12-30T01:39:26.937Z] info  Proxying code-server to Coder Cloud, you can access your IDE at https://xxx.cdr.co`

**Comment by pillows** [comment]
@J3n5en actually reading back at the messages, it may be this part where we are failing "Remember --link is a beta feature and requires being accepted for testing"

**Comment by code-asher** [comment]
I think it is still beta, but it no longer requires being accepted.

**Comment by lezwon** [comment]
Hi, I'm receiving the following error. Any idea about this?
```
!code-server --link
[2021-01-12T12:34:26.111Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-01-12T12:34:26.669Z] info  code-server 3.8.0 c4610f7829701aadb045d450013b84491c30580d
[2021-01-12T12:34:26.673Z] info  Using user-data-dir ~/.local/share/code-server
[2021-01-12T12:34:26.710Z] info  Using config file ~/.config/code-server/config.yaml
[2021-01-12T12:34:26.710Z] info  HTTP server listening on http://127.0.0.1:33187 (randomized by --link)
[2021-01-12T12:34:26.710Z] info    - Authentication is disabled (disabled by --link)
[2021-01-12T12:34:26.710Z] info    - Not serving HTTPS (disabled by --link)
[2021-01-12T12:34:26.726Z] info  Name must conform to regex ^[a-z][a-z0-9_]{0,50}$
[2021-01-12T12:34:26.736Z] error coder cloud agent exited with 1
```

**Comment by J3n5en** [comment]
> Hi, I'm receiving the following error. Any idea about this?
> 
> ```
> !code-server --link
> [2021-01-12T12:34:26.111Z] info  Wrote default config file to ~/.config/code-server/config.yaml
> [2021-01-12T12:34:26.669Z] info  code-server 3.8.0 c4610f7829701aadb045d450013b84491c30580d
> [2021-01-12T12:34:26.673Z] info  Using user-data-dir ~/.local/share/code-server
> [2021-01-12T12:34:26.710Z] info  Using config file ~/.config/code-server/config.yaml
> [2021-01-12T12:34:26.710Z] info  HTTP server listening on http://127.0.0.1:33187 (randomized by --link)
> [2021-01-12T12:34:26.710Z] info    - Authentication is disabled (disabled by --link)
> [2021-01-12T12:34:26.710Z] info    - Not serving HTTPS (disabled by --link)
> [2021-01-12T12:34:26.726Z] info  Name must conform to regex ^[a-z][a-z0-9_]{0,50}$
> [2021-01-12T12:34:26.736Z] error coder cloud agent exited with 1
> ```

@lezwon 

```
Name must conform to regex ^[a-z][a-z0-9_]{0,50}$
 ```
You should modify your computer name to match the regular expression🤔🤔

**Comment by lezwon** [comment]
It's in Google colab

**Comment by J3n5en** [comment]
> It's in Google colab

@lezwon  try to custom instance name by

```
code-server --link lezwon
```

**Comment by lezwon** [comment]
@J3n5en that worked. Thanks a lot mate. 👍

**Comment by pillows** [comment]
Unfortunately, it didn't work for me. Is there any settings I need to change or provide any logs that can help?

**Comment by mrfoxie** [comment]
> > It's in Google colab
> 
> @lezwon try to custom instance name by
> 
> ```
> code-server --link lezwon
> ```

i tried it on my colab but not working
![image](https://user-images.githubusercontent.com/25217451/106561568-f065f400-654e-11eb-9c18-38607d357894.png)

**Comment by lezwon** [comment]
Yea. it does not work for me anymore too. I'm not sure if colab is blocking tunnels.

**Comment by mrfoxie** [comment]
but i tried in my linux machine then it just end up I hope developers working on it

**Comment by code-asher** [comment]
There's a bug we're working on but for now if you access the IDE URL again it should work (the one that outputs from `--link`; refreshing the page shown in the screenshot won't work).

**Comment by sreya** [comment]
Your error should be fixed @mrfoxie

**Comment by mrfoxie** [comment]
> Your error should be fixed @mrfoxie.
> 
> @lezwon what sort of error message are you getting? If it's
> 
> ```
> An internal server error occurred
> ```
> 
> Would you mind pasting me the `id` that is returned?

![image](https://user-images.githubusercontent.com/25217451/107079929-913a0500-6816-11eb-80d5-685604b79694.png)
still I'm facing problem

**Comment by Genvara** [comment]
Reporting in that this still happens when using it in google colab.

**Comment by SamHep0803** [comment]
Having the same issue as OP, it was working fine yesterday when I tried it, however I woke up this morning and I'm getting "Error connecting to your code-server instance" when trying to access my server. I have tried this on both DigitalOcean and GCP so I have a feeling that it's an issue with cdr.

Nothing gets printed out to the stderr log file when running --log debug. It would be nice if I could get this working as I would like to get to development on my iPad.

**Comment by SamHep0803** [comment]
Actually something new, after I try and connect to the server, this doesn't happen straight away, but I eventually receive the message 

`[2021-02-16T09:59:22.641Z] info  2021/02/16 09:59:22 [ERR] yamux: Failed to read header: failed to get reader: failed to read frame header: EOF                                             [2021-02-16T09:59:22.645Z] info  2021-02-16 09:59:22.644 [WARN] <proxy.go:48>   code-server proxy exited      {"error": "accept tcp [::]:36221: use of closed network connection"}`

Hopefully this helps :)

**Comment by SamHep0803** [comment]
Just a sidenote, looking into the console when trying to connect to the page, I receive a 502 Bad Gateway error.

![image](https://user-images.githubusercontent.com/14109339/108050167-b0306680-7062-11eb-841f-32c5c6817eb4.png)
