### ISSUE TITLE
500 VS Code failed to load

### ISSUE THREAD

**Issue by sameetandpotatoes** [cdr/code-server#3325]
Hello, I know that this issue has been reported a few other times, but I'm still having this issue and I'm not sure how to resolve. My node version seems to satisfy requirements.

## OS/Web Information

- Web Browser: Chromium (Raspberry Pi)
- Local OS: macOS / iPad
- Remote OS: raspbian
- Remote Architecture:
- `code-server --version`: 3.9.3
- `npm --version`: 6.14.4
- `node --version`: v13.14.0
- `code --version`: 1.56.0

## Steps to Reproduce

1. Install vscode with ~~apt~~ yarn -> `yarn add code-server`
2. Run with `code-server`

```
$ which code-server
/home/pi/.yarn/bin/code-server
```

## Expected

VSCode should start up after entering my password.

## Actual

I enter my password, then I get the 500 error, VS Code failed to load. exited unexpectedly with code 0.

## Logs

`code-server --log debug`

```
$ code-server --verbose
[2021-05-08T21:53:14.959Z] info  code-server 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1
[2021-05-08T21:53:14.961Z] info  Using user-data-dir ~/.local/share/code-server
[2021-05-08T21:53:14.963Z] trace Using extensions-dir ~/.local/share/code-server/extensions
[2021-05-08T21:53:15.040Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-08T21:53:15.042Z] info  HTTP server listening on http://0.0.0.0:8081
[2021-05-08T21:53:15.043Z] info    - Authentication is enabled
[2021-05-08T21:53:15.044Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-05-08T21:53:15.045Z] info    - Not serving HTTPS
[2021-05-08T21:53:23.712Z] trace heartbeat
[2021-05-08T21:53:23.752Z] debug forking vs code...
[2021-05-08T21:53:25.747Z] error VS Code exited unexpectedly with code 0
```

## Notes
This issue can be reproduced in VS Code: Yes/**No**

## Hardware Info

```
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03111
Serial          : 100000003f8957b8
Model           : Raspberry Pi 4 Model B Rev 1.1
```

**Comment by jsjoeio** [comment]
I actually just set up code-server on my Raspberry Pi 4 last week. The installer script didn't seem to work (I have a note to update the docs). But installing via `npm` does. 

![image](https://user-images.githubusercontent.com/3806031/117704789-1b7c6700-b180-11eb-8608-9eaabbeb17ed.png)


Could you try that and report back?

**Comment by sameetandpotatoes** [comment]
I’m still having the issue. I just globally installed code-server with `npm install code-server -g`, and then ran `code-server` again. Same issue. Any ideas @jsjoeio? Should I have uninstalled code-server completely before doing that?

**Comment by sameetandpotatoes** [comment]
Interesting, I did try it again and got an error saying the cloud agent failed to download so `—link` wouldn’t work.

I also get warnings saying that `The engine “vscode” appears to be invalid`

**Comment by jsjoeio** [comment]
Oh yeah, we have an issue open about the cloud `--link` issue (see https://github.com/cdr/code-server/issues/3342#issuecomment-839519672). We're currently working on a patch for that. 

> also get warnings saying that The engine “vscode” appears to be invalid, 

Yeah, that is unfortunately expected and something we can't work around.

It sounds like your issue is fixed then. Can we close this?

**Comment by sameetandpotatoes** [comment]
Well, not quite - at the end of the day, it's still the same issue, no matter how I install it.

**Comment by jsjoeio** [comment]
We released `3.10.1` yesterday (see [release notes](https://github.com/cdr/code-server/releases/tag/v3.10.1)). Do you mind reinstalling code-server with `yarn` or `npm` and trying again?

**Comment by sameetandpotatoes** [comment]
I’m still getting the same issue. This is the version that was installed.

```
[2021-05-19T16:51:59.905Z] info  code-server 3.10.1 421237f499079cf88d68c02163b70e2b476bbb0d
```

**Comment by jsjoeio** [comment]
Hmm...do you mind updating the original reproduction steps and include the steps you use to access your code-server instance? Then I can investigate using my Pi.

**Comment by sameetandpotatoes** [comment]
> Hmm...do you mind updating the original reproduction steps and include the steps you use to access your code-server instance? Then I can investigate using my Pi.

Sorry for the late reply. I updated my original issue with hardware info on my Raspberry Pi (it’s revision 4 model b). I also put slightly more detailed steps, but it’s really just installing with yarn and running it. Let me know if there’s more I can provide.

**Comment by sameetandpotatoes** [comment]
@jsjoeio I’d be curious to know what versions of node and any other core dependencies you have installed on your Pi, so I can try to replicate with the same versions.

**Comment by sameetandpotatoes** [comment]
Ah I ended up getting it working!

Here's what I did:

```
$ yarn global add vscode
$ cd $(yarn global dir)/node_modules
$ yarn global add code-server
$ yarn --check-files
```
^ That told me the dependencies were messed up, specifically node 13.14.0 is not compatible. I thought it was since I read elsewhere that anything below v14 was going to work.

I lost the exact CLI output, but It said `10^ || 12^ || >= 14.0`, to my surprise.

So, using `nvm`, I uninstalled that: `nvm uninstall 13.14.0` and installed 12.0.0 `nvm install 12.0.0`.

Then, I made sure `code-server` binary was pointing to the binary directory under yarn (it was), and it worked!

**Comment by sameetandpotatoes** [comment]
I'll wait for @jsjoeio to close the issue in case there are any learnings or documentation updates to be made with this.

**Comment by code-asher** [comment]
Ahhhh I think we should make sure our documentation and checks all enforce the version of Node that VS Code ships with (was v12 but I think it's v14 as of 1.56).

**Comment by code-asher** [comment]
I opened https://github.com/cdr/code-server/issues/3458. I'll go ahead and close this issue; nice find by the way!!

**Comment by jsjoeio** [comment]
Great work @sameetandpotatoes 🙌 Glad you figured it out (and found a bug!). Like Asher said, we'll go make sure to fix that so others don't run into the same issue. Thanks again!
