### ISSUE TITLE
Cannot run jupyter kernel using python extension

### ISSUE THREAD

**Issue by simeneide** [cdr/code-server#3874]
I upgraded to the latest code-server today and now the jupyter interactive functionality of the python extension has stopped working. This happens both when I did this using a remote linux machine (docker based on the pytorch 1.9 image), AND when installing code-server on my local macbook. When opening a jupyter notebook a popup with the following information appears:

```Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)```

## OS/Web Information

- Web Browser: brave
- Local OS: macOs
- Remote OS: macos
- Remote Architecture: 
- `code-server --version`: 3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd

## Steps to Reproduce

On macos (m1):
1. install code-server using install script
2. install python extension (ms-python.python v2021.7.1060902895). This will also install a jupyter extension (ms-toolsai.jupyter v2021.6.832593372)
![image](https://user-images.githubusercontent.com/7136076/127607791-eba77701-7cef-4faa-ad44-21f548d3a0e2.png)

3. Try to open a new jupyter notebook (cmd+shift+p "Jupyter: Create new Blank Notebook")
![image](https://user-images.githubusercontent.com/7136076/127607905-f2119e1c-9fe4-4bbf-8854-435f88726c3a.png)
![image](https://user-images.githubusercontent.com/7136076/127608002-f08ba97f-e1c3-4cf2-a415-79fc74db2bb5.png)

The developer console has this error (which is too far in the deep for me to understand):
![image](https://user-images.githubusercontent.com/7136076/127608358-3213bd24-0950-4e49-b93b-06c333f099d4.png)

## Expected
A jupyter notebook starts up
## Actual
Error message 
```Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)```

**Comment by jsjoeio** [comment]
Thanks for opening the issue! I have never used jupyter notebooks.

Is it possible for you to update the repro steps? What do I need to install or how can I create a new jupyter notebook? Then I can try to reproduce locally and see how we can help you.

Thanks!

**Comment by simeneide** [comment]
> Is it possible for you to update the repro steps? What do I need to install or how can I create a new jupyter notebook? Then I can try to reproduce locally and see how we can help you.

Updated, thanks for coming back to me :) I thought "everyone" had this workflow, because it is such a good one ;)

**Comment by jsjoeio** [comment]
Thanks @simeneide for working with me (Python/Jupyter noob here).  That was very easy to follow and I received the same error as you.

## Video

(Apologies in advance if I pronounced your name wrong)
https://user-images.githubusercontent.com/3806031/127691663-7c037ef6-dad0-4342-a271-0470eaf3685a.mov

**Comment by balajib-b** [comment]
@simeneide the installed jupyter extension facilitates VS Code to interface with jupyter package installed in your env, it doesnt install jupyter notebook to your current environment. I would be happy if you could confirm that the python environment you are using has got jupyter installed.
Open terminal and type "python -m pip list" and check jupyter notebook and its dependent packages are installed. i have been using mixed stack of  code server, jupyter, miniconda, pytorch, tensorflow with no issues.
Also requesting you to use latest version of code server.

**Comment by simeneide** [comment]
Yes, all has and I am also able to start jupyter notebook. Currently using 3.11.0 as that is the latest found in brew (which is used when installing with the script). However, it fails much before it starts connecting to the jupyter kernel (as seen in video), so unsure if this is the problem. Are you not able to reproduce my steps? Alternatively, can you provide a step-by-step of how you get your setup to work?

Also: My steps above are working on 3.10, so something has happened.

**Comment by balajib-b** [comment]
@simeneide i doubt whether your jupyter installation is in path. there could be few more possibilities pertaining to this error. ping me at ji.balajib[at]gmail.com lets connect remote and debug. Im happy to help

 i think this way its going to be quick and then post back solution here. this could help @jsjoeio close few more issues.

**Comment by gogobd** [comment]
I have the very same problem in 3.11.1 and all previous versions. My last working configuration is code-server-3.9.3-linux-amd64. It would be great if Jupyter Notebooks could be fixed in current versions.

**Comment by jsjoeio** [comment]
Thanks for the notes @gogobd!

>  It would be great if Jupyter Notebooks could be fixed in current versions.

It's in the next milestone (3.12) so it will get worked on soon and should come in the next version. We have a couple competing priorities and an off-site this week so I can't promise when but keep an eye out!

**Comment by simeneide** [comment]
Do you know what is missing, @jsjoeio? Otherwise I am pretty sure I can cook up a simple docker image to reproduce this so that you can have a look, @balajib-b.

**Comment by jsjoeio** [comment]
I think I just need to dig into VS Code and figure out where `jupyter.createnewnotebook` is defined. I found it [here](https://github.com/microsoft/vscode/blob/main/extensions/vscode-notebook-tests/package.json#L27-L30) and it's [here](https://github.com/cdr/code-server/blob/main/lib/vscode/extensions/vscode-notebook-tests/package.json#L27-L30) in code-server. But the name is `vscode-notebook-tests` 🤔 I'd have to look closer at what's happening.

I'm not too familiar with how native VS Code commands/extensions get loaded but I'm guessing the issue lies there.

So maybe it's not being included in code-server's latest version for some reason 🤔 @code-asher may have some pro tips for debugging too, but this is where I would start. 

(Thanks for asking and offering to help though @simeneide super appreciated ♥️)

**Comment by balajib-b** [comment]
> Do you know what is missing, @jsjoeio? Otherwise I am pretty sure I can cook up a simple docker image to reproduce this so that you can have a look, @balajib-b.

that would be sufficient @simeneide , send me the yaml.

**Comment by im-coder-lg** [comment]
Have you tried Anaconda3 and Jupyter built inside Anaconda3?

**Comment by dthompson-maystreet** [comment]
@stefano can you provide any hints here, perhaps? You managed to get Jupyter running inside code-server successfully (though with a couple of issues - [#4013]

**Comment by sdissegna-maystreet** [comment]
Slightly older versions of the vscode-python and vscode-jupyter, i.e. the latest versions still compatible with vscode 1.57 seem to work out of the box.

**Comment by code-asher** [comment]
Assuming older versions of the extension work my guess is the extension
was updated and our marketplace had a snafu building the new extension
(as it seems to every time). Since we haven't switched to Open VSX yet
and we don't have a way to force the marketplace to stop updating
extensions automatically we may need to build it manually and overwrite
it (again...).

**Comment by fdasilva59** [comment]
Hi,

I am having the same issue with 
- code-server v3.11.1
- VS Code v1.57.1
- ms-python.python v2021.8.1159798656
- Jupyter ms-toolsai v2021.6.99, v2021.5.0 (also 2021.8.2031173646 is not compatible with VS Code v1.57.1)
(Note : I am also using an anaconda python environment, wher Jupyter is installed and is working fine)

=> Is there's somewhere a compatibility matrix of the code-server / VS Code / ms-toolsai versions to be used together and that are known to be functional ? 

Thx !

**Comment by code-asher** [comment]
I do not think we have anything like that unfortunately. We have some
comments about working versions but that is about it. Here are a few:

https://github.com/cdr/code-server/issues/3782#issuecomment-882715196
https://github.com/cdr/code-server/issues/2929#issuecomment-808774061
https://github.com/cdr/code-server/issues/2341#issuecomment-739562822
https://github.com/cdr/code-server/issues/2341#issuecomment-801450552

**Comment by gogobd** [comment]
Thank you, @benz0li for mentioning this here, I can confirm! I use docker to set up cdr code server and that's the first time in a long time this was working again:

```
## Code server
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -sfL https://github.com/cdr/code-server/releases/download/v3.12.0/code-server-3.12.0-linux-amd64.tar.gz | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-3.12.0-linux-amd64 ~/.local/lib/code-server-3.12.0
RUN ln -s ~/.local/lib/code-server-3.12.0/bin/code-server ~/.local/bin/code-server
RUN PATH="~/.local/bin:$PATH"

RUN curl -sfLO https://open-vsx.org/api/ms-toolsai/jupyter/2021.8.12/file/ms-toolsai.jupyter-2021.8.12.vsix \
 && curl -sfLO https://open-vsx.org/api/ms-python/python/2021.9.1218897484/file/ms-python.python-2021.9.1218897484.vsix \
 && ~/.local/bin/code-server --install-extension ./ms-toolsai.jupyter-2021.8.12.vsix || true \
 && ~/.local/bin/code-server --install-extension ./ms-python.python-2021.9.1218897484.vsix || true \
 && rm ms-toolsai.jupyter-2021.8.12.vsix \
 && rm ms-python.python-2021.9.1218897484.vsix
```

**Comment by huyiqun** [comment]
Using jupyter-2021.8.12 and python-2021.9.1218897484, still got the same issue.

**Comment by edvincent** [comment]
I'm think the problem is with the scraped extension?

```
[main 2021-09-17T01:28:50.508Z] RequestService#request https://extensions.coder.com/api/extensionquery
[main 2021-09-17T01:28:50.508Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-09-17T01:28:50.693Z] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-toolsai/jupyter/2021.8.12/Microsoft.VisualStudio.Code.Manifest
[main 2021-09-17T01:28:50.693Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-09-17T01:28:50.762Z] Started scanning system extensions
[main 2021-09-17T01:28:50.762Z] Started scanning user extensions
[main 2021-09-17T01:28:50.763Z] Scanned user extensions: 0
[main 2021-09-17T01:28:50.794Z] Scanned system extensions: 83
[main 2021-09-17T01:28:50.794Z] Installing extension: ms-toolsai.jupyter
[main 2021-09-17T01:28:50.795Z] Started scanning system extensions
[main 2021-09-17T01:28:50.795Z] Started scanning user extensions
[main 2021-09-17T01:28:50.796Z] Scanned user extensions: 0
[main 2021-09-17T01:28:50.825Z] Scanned system extensions: 83
[main 2021-09-17T01:28:50.825Z] Started downloading extension: ms-toolsai.jupyter
[main 2021-09-17T01:28:50.826Z] ExtensionGalleryService#download ms-toolsai.jupyter
[main 2021-09-17T01:28:50.826Z] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-toolsai/jupyter/2021.8.12/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true
```

That specific VSIX that gets returned from that coder marketplace is not complete. The `out` directly doesn't even have the `.out/client/extension` which is the [main of the package](https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L74).

I'm gonna guess that because [vscode-jupyter does not upload a VSIX in their releases](https://github.com/microsoft/vscode-jupyter/releases), so it's not only a scrape, but there are some extra build steps that are actually done on coder's side - but the build is failing and an incomplete extension is being generated and sent out?

Can someone check the builds logs of what's being scraped from that vscode-jupyter repo? I'm gonna assume that the `npm run package` is failing somewhere?

PS: The extension is also missing couple of the required python libraries actually. You're likely missing running pip and dumping those two libraries from requirements.txt in the pythonFiles folder, along the lines of

```
pip install -t ./pythonFiles/lib/python -r requirements.txt
```

**Comment by jsjoeio** [comment]
@edvincent thank you for the detailed notes! I think you hit the nail on the head. The scraped extension is in our custom extension marketplace (though we're trying to move away to the Open VSX one instead). I believe a previous maintainer (oxy) was the last one to update this. 

I think he had to manually build and upload it himself to get it working 🤔 

@code-asher do you remember how this works or do you know if we have any documentation around this?

**Comment by jtcole** [comment]
i just installed 3.12 clean (deleted all cache and configs) and still have the issue on ubuntu 20.04 lts.

**Comment by simeneide** [comment]
Again, thanks for looking into this. Although many similar comments, I can neither get this to work for 3.12.

**Comment by edvincent** [comment]
Here's a matrix table with links for those who want it working. The bottomline being: you can't use marketplace from code-server itself. You either need to manually download, drag-and-drop and install; or do something equivalent.

| code-server | vscode |                                                                                                                           ms-python.python                                                                                                                           |                                                                                                                                  ms-toolsai.jupyter                                                                                                                                  |
|:-----------:|:------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|    3.11.0   |  1.57  | v2021.8.1159798656<br>Installing from code-server's default marketplace: ✅<br>[Open VSX Download](https://open-vsx.org/extension/ms-python/python/2021.8.1159798656)<br>[GtiHub Download](https://github.com/microsoft/vscode-python/releases/tag/2021.8.1159798656) |                                           v2021.6.9999<br>Installing from code-server's default marketplace: ❌<br>[GitHub build artifact from microsoft/vscode-jupyter](https://github.com/microsoft/vscode-jupyter/actions/runs/966001402)                                          |
|    3.11.1   | 1.57.1 | v2021.8.1159798656<br>Installing from code-server's default marketplace: ✅<br>[Open VSX Download](https://open-vsx.org/extension/ms-python/python/2021.8.1159798656)<br>[GtiHub Download](https://github.com/microsoft/vscode-python/releases/tag/2021.8.1159798656) |                                           v2021.6.9999<br>Installing from code-server's default marketplace: ❌<br>[GitHub build artifact from microsoft/vscode-jupyter](https://github.com/microsoft/vscode-jupyter/actions/runs/966001402)                                          |
|     3.12    |  1.60  |  2021.9.1218897484<br>Installing from code-server's default marketplace: ✅<br>[Open VSX Download](https://open-vsx.org/extension/ms-python/python/2021.9.1218897484)<br>[GitHub Download](https://github.com/microsoft/vscode-python/releases/tag/2021.9.1218897484) | v2021.8.12<br>Installing from code-server's default marketplace: ❌<br>[Open VSX Download](https://open-vsx.org/extension/ms-toolsai/jupyter/2021.8.12)<br>[GitHub build artifact from microsoft/vscode-jupyter](https://github.com/microsoft/vscode-jupyter/actions/runs/1136758218) |

@jsjoeio What's the best way to help here? Build a working version myself and send it over? Try and figure out how to edit the current command so the process starts working again? Can we make your scraper use the build artifacts from their CI/CD releases? Try to engage the maintainers to put the link directly to the VSIX in their releases? Can we re-upload to coder's marketplace the VSIX from Open VSX?

**Comment by jsjoeio** [comment]
Thanks @edvincent for posting the matrix and offering to help! To be honest, the hardest part is finding time. I'm the only maintainer working full-time on code-server and I'm trying to juggle all the issues we have. My current priorities are improving the release process (see [milestone](https://github.com/cdr/code-server/milestone/30)). 

I've added this issue there as well but haven't been able to dive in yet. 

> What's the best way to help here?

Thank you for asking that! 

Well...we completely refactored how VS Code exists in the code-server codebase and it's in a funky place right now so it wouldn't be easy to get you into the codebase trying to edit the current command (we're lacking documentation cc @TeffenEllis).

> Can we make your scraper use the build artifacts from their CI/CD releases?

Maybe? I'm not super familiar with this part of our codebase yet and haven't had time to dive in.

> Try to engage the maintainers to put the link directly to the VSIX in their releases?

You could try this! I don't think we've had much success in the past though 😢

> Can we re-upload to coder's marketplace the VSIX from Open VSX?

If you have a working vsix file that works with the latest version of code-server and send that over here, that might be easy then for me to upload it to our marketplace 🤔 (at least I'm hopefully it's a simple CLI command to upload, I think it should be).

Otherwise, hoping to dive in on this issue this week! Just gotta wrap up another thing

**Comment by benz0li** [comment]
@edvincent Why not use the OpenVSX Registry by default? Sooner or later this will be the default for code-server.

According to [FAQ.md > How do I use my own extensions marketplace?](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#how-do-i-use-my-own-extensions-marketplace):

```bash
export SERVICE_URL=https://open-vsx.org/vscode/gallery
export ITEM_URL=https://open-vsx.org/vscode/item
```

ℹ️ This is working fine for my builds.

**Comment by jsjoeio** [comment]
I'm going to start working on this issue and use this comment as a place to document my notes. I will update it as I find more information so as to not spam the issue.

## Try to Reproduce Issue Locally

The first question is to see if this is still an issue. Here's how I'm going to try to reproduce it:
1. using code-server 3.12.0, run `code-server --extensions-dir cs-3874` (`cs-3874` is the name of an empty directory. I do this so I start code-sever with no extensions installed, a clean slate.)
2. Download the Python extension from Open VSX and manually install with `.vsix` file. 
3. Reload page in browser
4. Verify both Python and Jupyter are installed: `v2021.9.1230869389` and `v2021.8.12` respectively
5. Command Palette > Jupyter: Create New Blank Notebook

### Expected

A jupyter notebook starts up

### Actual

Command fails

![image](https://user-images.githubusercontent.com/3806031/134258696-5a526b07-b9e4-4c13-b655-da45d7c6b6b3.png)

✅ Confirmed. This issue still exists in code-server 3.12.0

### Notes

Based on the error in the console and the stack trace, it looks like we're missing a module in our fork of VS Code (you can tell because the stack points to `vendor/modules/code-oss-dev` which is where our fork of VS Code lives). 

```javascript
mainThreadExtensionService.ts:95 Activating extension 'ms-toolsai.jupyter' failed: Cannot find module '/Users/jp/Dev/repros/cs-3874/ms-toolsai.jupyter-2021.8.12/out/client/extension'
Require stack:
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/loader.js
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-fork.js.
```

Well actually, It looks like it can't find the module in `cs-3874/ms-toolsai.jupyter-2021.8.12/out/client/extension` 🤔

Let's go there and take a look...

**Comment by benz0li** [comment]
> Wait, no, Jupyter is open-source? https://github.com/microsoft/vscode-jupyter/releases/tag/2021.8.12

@jsjoeio Yes. This issue has only been resolved recently by https://github.com/microsoft/vscode-jupyter/pull/5812, which allowed updating both Python and Jupyter extensions on OpenVSX to a current version.  
ℹ️ [Don Jayamanne](https://github.com/donjayamanne/)'s [Python extension had been stuck at version 2020.10.332292344 on OpenVSX](https://github.com/eclipse/openvsx/issues/241) for months due to its dependency on the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) and the [runtime license](https://github.com/microsoft/vscode-jupyter/blob/e6e8961a9dba5e5929d53c6c943bc17d1e00de5b/extension_license.txt) of the latter.

**Comment by jsjoeio** [comment]
I installed with hombrew and we think the `postinstall` script isn't running which causes this.

GOOOD NEWS!! I'm on macOS and I installed code-server with the standalone method:

```shell
# install standalone method
curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone

# Run code-server
~/.local/lib/code-server-3.12.0 --auth none

# install 2021.8.12 from Open VSX
# https://open-vsx.org/extension/ms-toolsai/jupyter/2021.8.12
# install extension into code-server

# Jupyter: Create new Blank Notebook
```

So this works!!!

![image](https://user-images.githubusercontent.com/3806031/134434190-f45fbecb-a357-45bb-a3de-79e4d5db96ed.png)

We have narrowed down the error to the `postinstall.sh` script that is supposed to run after installing code-server locally. `npm-postinstall.sh`

We think it might be because we changed it from `sh` -> `bash` but we need to fix this (this was the only change)

**Comment by jsjoeio** [comment]
Okay we figured it out by adding `bash` as a dependency to the homebrew formula and it works locally.

![image](https://user-images.githubusercontent.com/3806031/134436458-6c929434-2da8-4ac5-aa59-00716544911e.png)

We should be running the `postinstall` with `sh`, but we made it run with `bash` because of Windows 🤔

Powershell doesn't have `sh` or `bash` by default 🤔 I think we need to revert this line until we can add proper Windows support, specifically revert this PR: https://github.com/cdr/code-server/pull/4116

Will discuss more tomorrow

**Comment by Craytor** [comment]
So should Jupyter now work after we update?

**Comment by jsjoeio** [comment]
> So should Jupyter now work after we update?

Once 3.12.1 is out, yes!

**Comment by im-coder-lg** [comment]
I have a (kind of) idea. Why not install Anaconda3? That has Jupyter Notebook built-in, so you can create a notebook from that, right?

**Comment by forkbabu** [comment]
> I have a (kind of) idea. Why not install Anaconda3? That has Jupyter Notebook built-in, so you can create a notebook from that, right?

nopes boy, error persists.

**Comment by simeneide** [comment]
> nopes boy, error persists.

according to @jsjoeio this will be fixed in 3.13 (separate issue). So Im waiting 😁

**Comment by im-coder-lg** [comment]
Wait I think it's 4.0.0, asked @jsjoeio two days ago and he said that it's straight to 4.0.0.

**Comment by im-coder-lg** [comment]
https://github.com/cdr/code-server/discussions/4490#discussioncomment-1633165

This was the reply, so there's no 3.12.1 or 3.12.2.

**Comment by jsjoeio** [comment]
Yes! Jupyter kernel should be working in the next release (it was 3.12.1 but it will be 4.0.0) as @im-coder-lg mentioned!

**Comment by simeneide** [comment]
Hi,
I downloaded 4.0.1 now and installed python+jupyter extensions. When starting a jupyter notebook I still get the `Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)` error.

**Comment by jsjoeio** [comment]
Hmm @simeneide I just tested this the other day [here](https://github.com/coder/code-server/issues/4689#issuecomment-1006132425) and it worked as expected. Can you take a look at that comment?

**Comment by simeneide** [comment]
yes sorry @jsjoeio , in my update I note that when I deleted my old config files it ran smoothing. dont know why, but it runs well now :)

**Comment by jsjoeio** [comment]
@simeneide hooray! Well I'm happy it was easy as that :) Thanks for confirming so quickly.
