### ISSUE TITLE
Make --open work in chromeOS

### ISSUE THREAD

**Issue by JamesGreenaway** [cdr/code-server#622]
sshcode has the functionality to open up code-server in my browser window. I think this is done using the command `www-browser --client --url http://www.google.com` for example, is it possible to have this feature in code-server?

**Comment by oonqt** [comment]
I think you're missing the point. The point of code-server is to be a server (being ran all the time), while sshcode is a code-server CLI to run it.

**Comment by JamesGreenaway** [comment]
I see your point however, for my use case, code-server act as a convenient way of running VSCode locally on a Chromebook without having to use the Linux app architecture.  With this workflow I have no need for sshcode, however I noticed that it was able to open Chrome in my browser from the crostini terminal. This was a nice touch, however if it is too much to ask then its not a problem.

**Comment by roberthmiller** [comment]
This issue has already solved here: https://github.com/cdr/sshcode/issues/78

**Comment by nhooyr** [comment]
@kylecarbs can you test it?

**Comment by kylecarbs** [comment]
This is still an issue, but seems to be really low prio. Will definitely re-open if many requests come in!
