### ISSUE TITLE
Compile Binary for Arm?

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#654]
## Description
I have a raspberry Pi 3b that I carry on me while at school, I have managed to reserve an IP for its MAC address with my school IT department (to run PHP-based web apps), but i cant use the docker image as docker itself kinda just hangs and does absolutely nothing, 

Is there a way I can use this on said Raspberry Pi? I run ArchLinux Arm on it, (aarch64)  and want to be able to run this program on it (preferably a binary, can compile if needed)

What would be needed to either 
A) Run it
or 
B) Compile a Binary for it?

This is what i get when i try to run via ``yarn start``

```
[alarm@alarm code-server]$ yarn start
yarn run v1.15.2
$ cd ./packages/server && yarn start
warning package.json: No license field
warning ../package.json: No license field
$ node --max-old-space-size=32384 --require ts-node/register --require tsconfig-paths/register src/cli.ts
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'ts-node/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:945:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:363:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:61:3)
    at internal/main/run_main_module.js:11:1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nol166** [comment]
Hey @Merith-TK, we are currently working on an ARM-based build for code-server but it's not quite ready yet. We will also need to trim the memory consumption before this would be practical for a Raspberry Pi. See #35

**Comment by Merith-TK** [comment]
Thanks, let me know on any progress

also the site is saying that they arnt accepting signups?

**Comment by nol166** [comment]
@Merith-TK That is correct, sign-ups for coder.com are currently disabled at the moment. We are working on a new user-facing product for the website

**Comment by Merith-TK** [comment]
Are there ways i can force it to compile for arm? I really am a newb to yarn

**Comment by crazyquark** [comment]
I tried to cross-build but I was hit by
#18 2921. ERROR BUILD:SERVER:BINARY:PACKAGE Failed: Failed to package binary: ✔ Wrote 1245 files!
#18 2921. ✔ Wrote 1 file!
#18 2921. Error: Forbidden
#18 2921.     at e.Binary.<anonymous> (/src/packages/server/node_modules/@coder/nbin/out/api.js:1:43397)
#18 2921.     at Generator.next (<anonymous>)
#18 2921.     at s (/src/packages/server/node_modules/@coder/nbin/out/api.js:1:40627)
#18 2921.     at process._tickCallback (internal/process/next_tick.js:68:7)
#18 2921. npm ERR! code ELIFECYCLE
#18 2921. npm ERR! errno 1
#18 2921. npm ERR! server@ build:binary: `ts-node scripts/nbin.ts`
#18 2921. npm ERR! Exit status 1
#18 2921. npm ERR! 
#18 2921. npm ERR! Failed at the server@ build:binary script.
#18 2921. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#18 2921. 
#18 2921. npm ERR! A complete log of this run can be found in:
#18 2921. npm ERR!     /root/.npm/_logs/2019-07-20T18_01_23_706Z-debug.log

Giving up for now...

**Comment by sr229** [comment]
Like we said @crazyquark, it needs to be fixed in our end first before you can self-build it for ARM. The memory usage is also way too high to be considered ready for Raspberry 3B+ (nbin only builds for amd64, not ARM atm).

**Comment by Merith-TK** [comment]
Xheesuz..

Issue number 18 just got spammed lol

**Comment by crazyquark** [comment]
All right, we'll wait quietly :)

**Comment by deansheather** [comment]
v2 is in the works, and should significantly reduce memory usage. We've merged ARM support into nbin, so we'll tackle ARM builds for code-server once we merge v2.

**Comment by sr229** [comment]
> v2 is in the works, and should significantly reduce memory usage. We've merged ARM support into nbin, so we'll tackle ARM builds for code-server once we merge v2.

(ARM Builds are still broken btw, working on it to fix everything else)

**Comment by code-asher** [comment]
Closing since we have https://github.com/cdr/code-server/issues/35.
